spring:
  profiles:
    active: default
  
  # Default configuration (for local development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis configuration (will be overridden in docker profile)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

# Disable MongoDB auto-configurations
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server:
  port: 7860

logging:
  level:
    root: INFO
    io.wingie: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# Application configuration
app:
  storage:
    screenshots: ./screenshots
    uploads: ./uploads
  
  selenium:
    timeout: 30s
    headless: true
    
  async:
    enabled: true
    max-concurrent-tasks: 3

# WebDriver Configuration
webdriver:
  enabled: true   # Set to false to disable WebDriver completely
  headless: true  # Set to true for headless operation
  retry:
    attempts: 3    # Number of initialization attempts
    delay: 2000    # Delay between retries in milliseconds
  # Chrome paths will be auto-detected or downloaded by WebDriverManager