spring:
  profiles:
    active: default
  
  # Default configuration (for local development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis configuration (will be overridden in docker profile)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

# Disable unused auto-configurations to prevent conflicts
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  # Note: Neo4j auto-configuration is kept enabled for future use
  # Redis auto-configuration is kept enabled for caching and pub/sub

server:
  port: 7860

logging:
  level:
    root: INFO
    io.wingie: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

# Application configuration
app:
  storage:
    screenshots: ./screenshots
    uploads: ./uploads
  
  playwright:
    timeout: 30000
    headless: true
    viewport:
      width: 1920
      height: 1080
    
  async:
    enabled: true
    max-concurrent-tasks: 3