spring:
  profiles:
    active: default
  
  # Jackson configuration for consistent timestamp handling
  jackson:
    time-zone: Europe/Amsterdam
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  
  # Default configuration (for local development with Docker PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/a2awebagent
    driver-class-name: org.postgresql.Driver
    username: agent
    password: agent123
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  
  # Redis configuration (will be overridden in docker profile)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# Disable unused auto-configurations to prevent conflicts
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  # Note: Neo4j auto-configuration is kept enabled for future use
  # Redis auto-configuration is kept enabled for caching and pub/sub

server:
  port: 7860

logging:
  level:
    root: INFO
    io.wingie: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    # AI Provider specific logging
    com.t4a: DEBUG                    # tools4ai framework
    com.t4a.processor: DEBUG          # AI processor calls
    org.springframework.cache: DEBUG  # Cache operations
    # MCP Controller debugging
    io.wingie.MCPController: DEBUG    # Custom cached controller
    io.github.vishalmysore.mcp.server: WARN  # Library controller (should be excluded)
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: ./logs/a2awebagent.log
    max-size: 10MB
    max-history: 10

# Application configuration
app:
  storage:
    screenshots: ./screenshots
    uploads: ./uploads
  
  playwright:
    timeout: 30000
    headless: true
    viewport:
      width: 1920
      height: 1080
    
  async:
    enabled: true
    max-concurrent-tasks: 3
  
  # Temp directory configuration (for Docker disk space issues)
  temp:
    custom:
      enabled: true
      dir: ./temp
  
  # MCP Controller Configuration
  mcp:
    custom:
      enabled: true          # Enable custom cached MCPController
    cache:
      enabled: true          # Enable PostgreSQL caching for tool descriptions
    fallback:
      enabled: true          # Enable fallback to basic mode if cache fails

# LLM Call Tracking Configuration
llm:
  tracking:
    enabled: true            # Enable LLM call tracking via AOP
    log-payloads: false      # Log request/response payloads (for debugging only)
    cost-estimation: true    # Enable cost calculation
    cache-correlation: true  # Track cache hit/miss correlation

# Cache configuration
cache:
  warming:
    enabled: true
    delay:
      seconds: 30
  response:
    enabled: true
  web:
    automation:
      enabled: true